/**
 * Unit tests for daily-compaction.
 *
 * Mocks the Anthropic SDK so we exercise the prompt-construction and
 * response-parsing logic without making real API calls. The end-to-end
 * runDailyCompaction wrapper requires GitHub + Telegram env to instantiate
 * its cron-runner shell, so we test the behavior-bearing helpers directly.
 */

import { jest, describe, it, expect, beforeEach, afterEach } from "@jest/globals";

// Mock Anthropic SDK BEFORE importing the module under test (ESM rules).
const mockCreate = jest.fn();
jest.unstable_mockModule("@anthropic-ai/sdk", () => ({
  default: jest.fn().mockImplementation(() => ({
    messages: { create: mockCreate },
  })),
}));

const { __testing } = await import("./daily-compaction.js");
const { addMessage, getAllMessages, clearMessages } = await import("../bot/message-history.js");

describe("daily-compaction / formatTranscript", () => {
  beforeEach(() => clearMessages());
  afterEach(() => clearMessages());

  it("renders user and coach messages with timestamps and role labels", () => {
    addMessage("First set goblet @ 60.", true);
    addMessage("Goblet squat 60×8 logged.", false);

    const transcript = __testing.formatTranscriptForTest(getAllMessages());
    expect(transcript).toContain("**User**");
    expect(transcript).toContain("**Coach**");
    expect(transcript).toContain("First set goblet @ 60.");
    expect(transcript).toContain("Goblet squat 60×8 logged.");
    // ISO timestamps are present for each entry.
    expect(transcript).toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
  });

  it("returns empty string when no messages", () => {
    expect(__testing.formatTranscriptForTest([])).toBe("");
  });
});

describe("daily-compaction / buildSummaryFile", () => {
  it("includes auto-generated marker, date, message count, and the summary body", () => {
    const file = __testing.buildSummaryFile(
      "## Active threads\n- Switch to back squat next leg day",
      "2026-05-06",
      42
    );
    expect(file).toContain("Auto-generated by daily-compaction");
    expect(file).toContain("2026-05-06");
    expect(file).toContain("42 msgs compacted");
    expect(file).toContain("Switch to back squat next leg day");
  });
});

describe("daily-compaction / summarizeTranscript", () => {
  const originalEnv = process.env;

  beforeEach(() => {
    mockCreate.mockReset();
    process.env = { ...originalEnv, ANTHROPIC_API_KEY: "test-key" };
  });

  afterEach(() => {
    process.env = originalEnv;
  });

  it("calls Haiku with the transcript and parses the text response", async () => {
    mockCreate.mockResolvedValueOnce({
      content: [{ type: "text", text: "## Active threads\n- Carry-over thread" }],
    } as never);

    const result = await __testing.summarizeTranscript(
      "### 2026-05-06T01:00:00Z — **User**\n\nFirst set goblet @ 60.",
      null,
      "2026-05-06"
    );

    expect(result).toBe("## Active threads\n- Carry-over thread");
    expect(mockCreate).toHaveBeenCalledTimes(1);

    const call = mockCreate.mock.calls[0][0] as {
      model: string;
      system: string;
      messages: { role: string; content: string }[];
    };
    expect(call.model).toBe("claude-haiku-4-5");
    expect(call.system).toContain("coaching memory compactor");
    expect(call.messages[0].content).toContain("2026-05-06");
    expect(call.messages[0].content).toContain("First set goblet");
  });

  it("includes yesterday's summary in the prompt when provided", async () => {
    mockCreate.mockResolvedValueOnce({
      content: [{ type: "text", text: "ok" }],
    } as never);

    await __testing.summarizeTranscript(
      "transcript body",
      "## Active threads\n- Knee discomfort, watch on Tuesday",
      "2026-05-06"
    );

    const call = mockCreate.mock.calls[0][0] as {
      messages: { role: string; content: string }[];
    };
    expect(call.messages[0].content).toContain("Previous summary");
    expect(call.messages[0].content).toContain("Knee discomfort");
  });

  it("throws when the model returns an empty response", async () => {
    mockCreate.mockResolvedValueOnce({ content: [] } as never);

    await expect(__testing.summarizeTranscript("transcript", null, "2026-05-06")).rejects.toThrow(
      "empty response"
    );
  });

  it("throws when ANTHROPIC_API_KEY is unset", async () => {
    delete process.env.ANTHROPIC_API_KEY;
    await expect(__testing.summarizeTranscript("transcript", null, "2026-05-06")).rejects.toThrow(
      "ANTHROPIC_API_KEY"
    );
  });
});

describe("daily-compaction / message-history helpers", () => {
  beforeEach(() => clearMessages());
  afterEach(() => clearMessages());

  it("getAllMessages returns every stored message, oldest first", () => {
    addMessage("one", true);
    addMessage("two", false);
    addMessage("three", true);

    const all = getAllMessages();
    expect(all.map((m) => m.text)).toEqual(["one", "two", "three"]);
    expect(all[0].isFromUser).toBe(true);
    expect(all[1].isFromUser).toBe(false);
  });

  it("clearMessages empties the store so the next day starts fresh", () => {
    addMessage("yesterday", true);
    expect(getAllMessages()).toHaveLength(1);

    clearMessages();
    expect(getAllMessages()).toHaveLength(0);
  });
});
